import QtQuick 2.15
import QtQuick.Window 2.15
import QtQuick.Controls 2.15

ListModel {
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}
    ListElement{value_indicator: "value";bold: "false"}

}
